cluster.name: "docker-cluster"
node:
  master: true
  data: true
  max_local_storage_nodes: 2
bootstrap:
  system_call_filter: false
  memory_lock: false
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2
