version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.zen.ping.unicast.hosts=elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/var/log/elasticsearch
      - ./elasticsearch/config/elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch2
    environment:
      - node.name=es02
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/var/log/elasticsearch
      - ./elasticsearch/config/elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  # elasticsearch3:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
  #   container_name: elasticsearch3
  #   environment:
  #     - node.name=es03
  #     - node.master=true
  #     - node.data=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.zen.ping.unicast.hosts=elasticsearch
  #   ulimits:
  #     nproc: 65535
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./elasticsearch/data:/usr/share/elasticsearch/data
  #     - ./elasticsearch/logs:/var/log/elasticsearch
  #     - ./elasticsearch/config/elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   networks:
  #     - esnet

  # kibana:
  #   image: 'docker.elastic.co/kibana/kibana:6.5.0'
  #   container_name: kibana
  #   links:
  #     - elasticsearch:elasticsearch
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - esnet

networks:
  esnet: